/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dock: typeof import('./src/components/dock.vue')['default']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElTree: typeof import('element-plus/es')['ElTree']
    FileDialog: typeof import('./src/components/file-dialog.vue')['default']
    Filetree: typeof import('./src/components/filetree.vue')['default']
    Tab: typeof import('./src/components/tab.vue')['default']
  }
}
